# Generated by Django 3.2.8 on 2021-10-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_orderproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumer',
            options={'verbose_name': 'Consumer', 'verbose_name_plural': 'Consumers'},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'verbose_name': 'Provider', 'verbose_name_plural': 'Providers'},
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category'),
        ),
    ]
