# Generated by Django 3.2.8 on 2021-11-03 12:09

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20211103_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='crop',
        ),
        migrations.AddField(
            model_name='product',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '100x100', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
